tm_chat:
    path:      /chat/{id}
    defaults:
        _controller: TMChatBundle:Chat:user
        id: ''
    requirements:
        id: \d+

tm_chat_new_message:
    path:      /new-message/{id}
    defaults:
        _controller: TMChatBundle:Chat:newMessage
    requirements:
        id: \d+