tm_core:
    resource: "@TMCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@TMUserBundle/Resources/config/routing.yml"

tm_chat:
    resource: "@TMChatBundle/Resources/config/routing.yml"