# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    tm.twig.country_extension:
        class: TM\PlatformBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension }
    tm.comment_voter:
        class:  TM\PlatformBundle\Security\CommentVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
    tm.travel_voter:
        class:  TM\PlatformBundle\Security\TravelVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
    tm.user_voter:
            class:  TM\UserBundle\Security\UserVoter
            arguments: ['@security.access.decision_manager']
            public: false
            tags:
                - { name: security.voter }