# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    tm.twig.country_extension:
        class: TM\PlatformBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension }