tm_platform_search:
    path:      /page/{page}
    defaults:
        _controller: TMPlatformBundle:Travel:search
        page:        1
    requirements:
        page: \d*

tm_platform_view:
    path:      /travel/{id}
    defaults:
        _controller: TMPlatformBundle:Travel:view
    requirements:
        id: \d+

tm_platform_map:
    path:     /map
    defaults:
        _controller: TMPlatformBundle:Travel:map

tm_platform_ajax_last_travel:
    path:     /ajaxLastTravel/{code}
    defaults:
        _controller: TMPlatformBundle:Travel:ajaxLastTravel
    options:
        expose: true
    requirements:
        code: "[A-Z]{2}"

tm_platform_ajax_set_session_country_code:
    path:     /ajaxSetSessionCountryCode/{code}
    defaults:
        _controller: TMPlatformBundle:Travel:ajaxSetSessionCountryCode
    options:
        expose: true
    requirements:
        code: "[A-Z]{2}"

tm_platform_add:
    path:     /add
    defaults:
        _controller: TMPlatformBundle:Travel:add

tm_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: TMPlatformBundle:Travel:edit
    requirements:
        id: \d+

tm_platform_remove_comment:
    path:      /remove/{id_travel}/{id_comment}
    defaults:
        _controller: TMPlatformBundle:Comment:removeComment
    requirements:
        id_travel: \d+
        id_comment: \d+