tm_platform_home:
    path:      /page/{page}
    defaults:
        _controller: TMPlatformBundle:Travel:index
        page:        1
    requirements:
        page: \d*

tm_platform_view:
    path:      /travel/{id}
    defaults:
        _controller: TMPlatformBundle:Travel:view
    requirements:
        id: \d+

tm_platform_add:
    path:     /add
    defaults: { _controller: TMPlatformBundle:Travel:add }

tm_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: TMPlatformBundle:Travel:edit
    requirements:
        id: \d+

tm_platform_edit_comment:
    path:      /edit/{id_travel}/{id_comment}
    defaults:
        _controller: TMPlatformBundle:Travel:editComment
    requirements:
        id_travel: \d+
        id_comment: \d+

tm_platform_remove_comment:
    path:      /remove/{id_travel}/{id_comment}
    defaults:
        _controller: TMPlatformBundle:Travel:removeComment
    requirements:
        id_travel: \d+
        id_comment: \d+