<?php

namespace TM\PlatformBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $code
     * @return array
     */
    public function getAllTravelCountryCode($code)
    {
        $query = $this->createQueryBuilder('c');
        $query->select('c')
            ->where('c.code = :code')
            ->setParameter('code', $code);
        return $query->getQuery()->getResult();
    }
}
